 version: '2'
 services:
   redis1:
     container_name: redis1-container
     image: redis:3.0.7-alpine
     ports:
       - "16379:6379"
     command: redis-server --requirepass 12345asdg
     restart: always
#   mysql1:
#     image: mysql:5.7
#     ports:
#      - "33306:3306"
#     container_name: mysql1-container
#     volumes:
#      - ./my-binlog.cnf:/etc/mysql/conf.d/mysql.cnf
#      - /var/lib/mysql
#     env_file:
#      - ./mysql.env
#     command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
#     restart: always
#   mysql2:
#     image: mysql:5.7
#     ports:
#      - "33307:3306"
#     container_name: mysql2-container
#     volumes:
#      - ./my-binlog.cnf:/etc/mysql/conf.d/mysql.cnf
#      - /var/lib/mysql
#     env_file:
#      - ./mysql.env
#     command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
#     restart: always